[WIP] #67 Damage Indicators
TTTReborn/tttreborn pull request #85
Opened 2021-06-27 11:30 UTC by Westsaid

![image](https://user-images.githubusercontent.com/58175915/123542662-28aede80-d74b-11eb-92c0-cdce3aa40e15.png)

To discuss: How do we want to group the damage indicator text?

health>75 : "Healthy"
health>20 : "Injured"
else : "Near death"
Whats your opinion?

TODO: 
- Color the damageIndicator label.
- Remove the role coloring of the Nameplate bg to ensure contrast ratio to the color of the damageIndicator label.
  I thought about adding a colored dot before the playername like on the scoreboard.

2021-06-27 20:15 UTC, Alf21 commented
I like what you did, but idk about the change of the role displaying <https://user-images.githubusercontent.com/58175915/123549032-90732280-d767-11eb-928e-19bb226d9d23.png>, maybe we need something like a team indicator so you can easily and fast detect a teammember :)

2021-06-27 20:18 UTC, Alf21 commented
And we need a damage overlay if you getting hit (what I initially meant with "DamageIndicator" :D) like seen here <https://youtu.be/sLgqtRUuYB4?t=30>

2021-06-27 20:42 UTC, Westsaid commented
@Alf21 I agree it might be a bit hard to quickly identify a T-mate... The best way to achieve this is imo to implement a 3D UI element which is floating over him, in that case you would also be able to see him far across the map. 

Meanwhile speaking of the nameplate here are all the options I currently have in my mind:
- Bg in role colors just like before: Hardly compatible with the colored health text...
- Dot like currently
- Colored 2px borders: 
![image](https://user-images.githubusercontent.com/58175915/123558727-16a75d00-d798-11eb-9350-aa3f19e2957f.png)
-  Colored name underline
![image](https://user-images.githubusercontent.com/58175915/123558841-b95fdb80-d798-11eb-9302-07d6757b2ef5.png)

2021-06-27 22:28 UTC, Alf21 commented
Hmmm... Idk tbh, but if I had to choose, I'd take the border solution

2021-06-28 00:45 UTC, mzegar commented
Not sure if I'm in the minority, but I'd prefer removing the black transparent square and make it similar to TTT. I like the dot, and the coloured damage indicator label. Thoughts?

2021-06-28 07:40 UTC, Westsaid commented
@mzegar We could try and see... the bg is to ensure contrast and the ability to easily read the text...

2021-06-28 07:50 UTC, TimGoll commented
In TTT2 I added a colored role icon next to the player name

2021-06-29 21:02 UTC, Westsaid commented
I've implemented the bordered version and did some adjustments, this is ready from my pov.
![image](https://user-images.githubusercontent.com/58175915/123866220-11c7e200-d92d-11eb-94a8-4fb3e3bc5a71.png)

2021-06-30 16:47 UTC, Alf21 requested changes

2021-06-30 16:47 UTC, Alf21 commented on code/player/TTTPlayer.Lookup.cs
> +                    return;
```suggestion
```

2021-06-30 16:47 UTC, Alf21 commented on code/player/TTTPlayer.Lookup.cs
> +                    if (!player.IsValid())
This can be merged with just `if player.IsValid()` afaik

2021-06-30 16:47 UTC, Alf21 commented on code/player/TTTPlayer.Lookup.cs
> +                To client = To.Single(this);
Declaration isn't needed and can be used inline.

2021-06-30 16:47 UTC, Alf21 commented on code/player/TTTPlayer.RPCs.cs
> +        public static void SetNameplateHealth(float health)
```suggestion
        public static void ClientSetNameplateHealth(float health)
```

2021-06-30 16:47 UTC, Alf21 commented on code/ui/Nameplate.cs
> +            Color near_death = Color.FromBytes(252, 42, 42);
Maybe we should put this into a struct or smth like this

2021-06-30 16:47 UTC, Alf21 commented on code/player/TTTPlayer.Lookup.cs
> +                    SetNameplateHealth(client, player.Health);
If we would use a struct like suggested, we don't need to send the full exact health but could instead just send a string as a health indicator (used to fetch the right state). But as AC doesn't care as much, we don't need this.

2021-07-01 01:27 UTC, mzegar requested changes
I've already expressed my opinion on how I feel about the large black background, so if everyone else is likes it, go with it 👍 .

Personally, I hate having a large UI pop up near the crosshair.

2021-07-01 01:27 UTC, mzegar commented on code/ui/Nameplate.cs
> +                : near_death;
Should const these values up above for easy access `70`, `20`.

2021-07-01 01:27 UTC, mzegar commented on code/ui/Nameplate.cs
> +                : "Near death";
Same as other comment, we should const these magic numbers. And even potentially the strings themself.

2021-07-03 12:29 UTC, Alf21 approved these changes

2021-07-04 00:32 UTC, mzegar approved these changes

2021-07-04 00:50 UTC, merged